# Generated by Django 5.2.4 on 2025-07-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='habit',
            name='done_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_per_day',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
